export const PERFORMING_SIGNUP = "PERFORMING_SIGNUP";
export const PERFORMING_SIGNUP_SUCCESS = "PERFORMING_SIGNUP_SUCCESS";
export const PERFORMING_SIGNUP_FAILED = "PERFORMING_SIGNUP_FAILED";

export const PERFORMING_SIGN_IN = 'PERFORMING_SIGN_IN';
export const PERFORMING_SIGN_IN_SUCCESS = 'PERFORMING_SIGN_IN_SUCCESS';
export const PERFORMING_SIGN_IN_FAILED = 'PERFORMING_SIGN_IN_FAILED';

export const PERFORMING_SIGNOUT = "PERFORMING_SIGNOUT";
export const PERFORMING_SIGNOUT_SUCCESS = "PERFORMING_SIGNOUT_SUCCESS";
export const PERFORMING_SIGNOUT_FAILED = "PERFORMING_SIGNOUT_FAILED";

export const SENDING_MESSAGE_START = "SENDING_MESSAGE_START";
export const SENDING_MESSAGE_SUCESS = "SENDING_MESSAGE_SUCESS";
export const SENDING_MESSAGE_FAILED = "SENDING_MESSAGE_FAILED";


export const DELETING_MESSAGE = "DELETING_MESSAGE";
export const DELETING_MESSAGE_SUCESS = "DELETING_MESSAGE_SUCESS";
export const DELETING_MESSAGE_FAILED = "DELETING_MESSAGE_FAILED";

export const NEW_USER_JOIN_SUCCESS = "NEW_USER_JOIN_SUCCESS";